- src/event.js
- test/event.html
Move the parameter data to callback, if callback is undefined or data is
false. As the data can hold any type, including function, the check is
done on the callback, to see if it is undefined, before moving the
parameters.
Fixes #1042
> Accept function as data for on event handler

- src/zepto.js
- test/zepto.html
Calling `.getBoundingClientRect` on elements not in the DOM throws an `Unspecified error` on IE 10, what I did here is the same approach used by [jQuery's offset](https://github.com/jquery/jquery/blob/74ae5444832b2fb966768a97281d2ad8c088bc58/src/offset.js#L97-L99) implementation.
> Fix error in offset call on IE10

- src/ajax.js
This comment is added to avoid future question about `urlAnchor.href` self assignment, see #1085.
> add comment about `urlAnchor.href` self assignment

- README.md
Not sure if people are still complaining, but in case you want to include this, I set up a [demo](https://github.com/silvenon/zepto-module-demo) where I shimmed Zepto for browserify without touching the source code. You can still import only modules you need, rather than having to import all of Zepto, which is nice.
I'm not even using Zepto, but attempting to demonstrate to other people that you guys don't have to do :hankey: for people to use Zepto as modules was a fun process.
Of course, feel free to turn it down or rephrase.
> Add note about JS module loaders

- src/zepto.js
- test/zepto.html
Previously it only returned the text from the first item matching the selector passed. 
Now it returns the text concatenated from all selectors matching the selector passed. 
#1142
> text() returns text from all matching selectors instead of just the first one

- src/ajax.js
> The `responseText` property of the XMLHttpRequest object can be set to change the expected response type from the server.
See: [MDN Sending and Receiving Binary Data](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data)
The `responseText` property **should not be accessed**, when the `responseType` enumerated value of the XMLHttpRequest object has been set to `arraybuffer` or `binary`.
Accessing the `responseText` value of an `arraybuffer` XMLHttpRequest throws an error (see below).
Example:
```
$.ajax({
url: 'http://joeschmoe.org/image.png',
timeout: 1000,
beforeSend: function(xhr) {
xhr.responseType = 'arraybuffer';
return xhr;
},
success: function(response) {
// Response type is ArrayBuffer (native XMLHttpRequest)
var data = new …
```
> Ajax: Add support for receiving binary data (bug)

- src/zepto.js
- test/zepto.html
- fixes `offset()` on `document.documentElement`, which also affected `$('html').width()`, related to #1158
- removes some trailing whitespaces in test/zepto.html
> fixes offset() on documentElement, related to #1158

- src/ajax.js
- test/ajax.html
- test/server.coffee
Original Issue: https://github.com/madrobby/zepto/issues/1194 . I did not get any objections, so I went for it. Should work the same as it would on jQuery. I tried to keep my changes compliant to the Zepto StyleGuide. 
I appreciate any feedback. Let me know if you have any concerns. 
I ran all tests, with the addition of the tests I added, they all pass. 
Thanks!
> Added datafilter option to Zepto ajax.js.

- src/event.js
The following warnings are observed in Chrome 45.0 and 47.0 (OSX):
`'webkitMovementX' is deprecated. Please use 'movementX' instead.`
`webkitMovementX/Y` seem to be deprecated in Chrome 45+, so skip copying them.
This fix eliminates these warnings.
> Skip copying webkitMovementX/Y

- src/zepto.js
This should fix an issue with embedded scripts that are injected in a dynamically created IFRAME. If this operation is performed in the top window then the script is always evaluated there.
> Multi-windows support for embedded scripts

- src/zepto.js
- test/zepto.html
- fixes `$().css({height:1}).css({height:1})`
- adds test cases
- fixes #1145
Have tried my best to obey the original coding style. Duplicate `getComputedStyle(element, '')`, but it will not become much larger after compressing.
> fixes css batch setting on non-existing element, fixes #1145

- .npmignore
- make
- package.json
This improves our npm package. The release process is now:
1. Bump version number in only 1 location, `package.json`;
2. Create a tagged commit `vX.Y.Z` that matches package.json;
3. `./make publish`.
> Add `make publish` target for npm

- README.md
- make
- src/amd_layout.js
When a module loader is present at runtime, this wraps Zepto as an anonymous module. It still exports `Zepto` and `$` to the global namespace when imported, though, to keep compatibility with plugins that expect it there. This is [akin to what jQuery does](https://github.com/jquery/jquery/pull/557).
With no module loader, zepto.js executes normally.
Opt out of this AMD shim by setting `NOAMD=1` environment variable.
References #342, #797 #1030 #1039;
fixes #1052, fixes #955, fixes #900, fixes #751, fixes #708.
> Enable AMD-compatible module output

- src/event.js
The `event.timeStamp` property is considered readonly by safari on iOS
(iOS 9.3.4, Safari 9) and assigning it throws an error which effectively
disables at least `.on()` and `.click()` listeners. This fixes #1209.
> Catch exception while assigning `event.timeStamp`

- src/zepto.js
- test/zepto.html
This commit is revisiting of the following commit.
commit 790d6c29f108777f4420b25ea6894e3f3028ca85
Author: sgtwilko null@sgtwilko.f9.co.uk
Date:   Wed Oct 2 10:47:09 2013 +0100
```
Ready fires on IE10 before the document is ready.
Added additional check for document.body into the ready check.
Changing the readyRE regex does resolve the issue on IE, but breaks
Chrome.  Adding this check fixes IE and doesn't seem to have any
problems on Chrome/Firefox.
```
More info about the original problem with IE can be found in related
jQuery tracker [1](https://bugs.jquery.com/ticket/12282).
This commit solves the particular case when IE <= 10 gives non-null
`document.body` in "interactive" `document.readyState`, but DOM isn't
fully parsed at the moment. The case was catched in …
> More reliable way to examine DOM readiness on IE

- src/zepto.js
- test/zepto.html
This form, which accepts an object of property-value pairs, has been
present in jQuery since 1.6 ([http://api.jquery.com/prop/#prop-properties](http://api.jquery.com/prop/#prop-properties)).
I also flipped the logic of the ternary operator so that it parallels the `attr` method.
> Add object form to prop method

- src/zepto.js
- test/zepto.html
As discussed in issue #1242 passing nodes in $.is() is used within Bootstrap.
This PR adds support for those use cases
> Added support for passing nodes in $.is()

- src/amd_layout.js
This fixes an issue when using zepto with Browserify. To prevent scope leakage, browserify wraps modules in a function. `this` becomes the scope of that function, and not `window`.
Will solve:
- https://github.com/madrobby/zepto/issues/1222
- https://github.com/madrobby/zepto/issues/1210
> Explicitly use window

- src/zepto.js
- test/zepto.html
I messed up with PR #1300 - short/lowercase property names like class, readonly, etc. were not being translated in the new object form of the `prop` method. This patch fixes it.
> Fix object form of prop method: translate names

- README.md
http://github.e-sites.nl/zeptobuilder/ is a dead page. Looks like the Wayback Machine doesn't have anything there since 2015.
> Update README. Looks like Zepto Builder website is dead.
